<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NetZapret.Core\NetZapret.Core.csproj" />
    <ProjectReference Include="..\NetZapret.Proxy\NetZapret.Proxy.csproj" />
    <ProjectReference Include="..\NetZapret.Zapret\NetZapret.Zapret.csproj" />
  </ItemGroup>

</Project>
