<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NetZapret.Core\NetZapret.Core.csproj" />
    <ProjectReference Include="..\NetZapret.Subscriptions\NetZapret.Subscriptions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NetZapret.Core.Tests" />
  </ItemGroup>

</Project>
